apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  name: meteorjs
spec:
  tags:
  - annotations:
      description: Build and run MeteorJS applications
      iconClass: icon-nodejs
      sampleRepo: https://github.com/getupcloud/meteorjs-ex.git
      supports: meteorjs:4.1,meteorjs:nodejs
      tags: builder,meteorjs
      version: "4.1"
    from:
      kind: DockerImage
      name: getupcloud/centos7-s2i-meteorjs:4.1
    name: "4.1"
  - annotations:
      description: Build and run MeteorJS applications
      iconClass: icon-nodejs
      sampleRepo: https://github.com/getupcloud/meteorjs-ex.git
      supports: meteorjs:latest,meteorjs:4.1,meteorjs:nodejs
      tags: builder,meteorjs
      version: "latest"
    from:
      kind: ImageStreamTag
      name: "4.1"
    name: "latest"
